# Generated by Django 4.0.3 on 2022-05-03 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0006_semester_alter_customuser_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='semester_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='student_management_app.semester'),
        ),
    ]
