# Generated by Django 4.0.3 on 2022-05-11 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0011_remove_subjects_oe_course_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects_oe',
            name='course_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student_management_app.courses'),
        ),
    ]
