# Generated by Django 4.0.3 on 2022-05-11 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0014_subjects_oe_created_at_subjects_oe_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects_oe',
            name='semester_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='student_management_app.semester_oe'),
        ),
    ]
