# Generated by Django 4.0.3 on 2022-05-22 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0015_alter_subjects_oe_semester_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='usn_num',
            field=models.CharField(default=1, max_length=255),
        ),
    ]
