# Generated by Django 4.0.3 on 2022-05-23 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0018_customuser_random_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='random_key',
        ),
    ]
