# Generated by Django 4.0.3 on 2022-06-26 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0021_forms_oe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forms_oe',
            old_name='semester_id',
            new_name='semester_name',
        ),
    ]
