# Generated by Django 4.0.3 on 2022-06-26 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0022_rename_semester_id_forms_oe_semester_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forms_oe',
            name='subject_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='student_management_app.subjects_oe'),
        ),
    ]
