# Generated by Django 4.0.3 on 2022-06-27 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0023_alter_forms_oe_subject_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forms_oe',
            name='username',
        ),
    ]
