# Generated by Django 3.1.7 on 2022-06-28 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0026_forms_oe_semester_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects_oe',
            name='semester_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student_management_app.semester_oe'),
        ),
    ]
