# Generated by Django 3.1.7 on 2022-06-28 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0027_auto_20220628_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forms_oe',
            name='semester_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student_management_app.semester_oe'),
        ),
        migrations.AlterField(
            model_name='forms_oe',
            name='subject_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student_management_app.subjects_oe'),
        ),
        migrations.AlterField(
            model_name='forms_oe',
            name='username',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
